[tool.ruff]
extend-exclude = [
    "__pycache__",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E", "W",
    # flake8
    "F",
    # isort
    "I",
    # pytest style
    "PT",
    # eradicate commented code
    "ERA",
    # ruff lint
    "RUF",
]
ignore = [
    # `format` will wrap lines.
    "E501",
    # FIXME: pytest-fixture-no-parentheses
    "PT001",
    "PT023",
    # FIXME: pytest-raises-too-broad
    "PT011",
    # FIXME: parenthesize-chained-operators
    "RUF021",
]

[tool.ruff.lint.isort]
known-first-party = ["dockerflow"]
